### ISSUE TITLE
Error "error: command 'x86_64-linux-gnu-gcc' failed with exit status 1"

### ISSUE THREAD

**Issue by vatsal28** [sirfz/tesserocr#94]
I'm getting the following error when installing tesserocr. 

I've tried the following:

- Built tesseract from source
- Built leptonica from source 
- Fixed all the environment variables
- Tried the different CPP flags (including DUSE flag)
- Tried pip and setup.py for tesserocr

I'm still getting the following error (Ubuntu 14.04):

      CPPFLAGS=-I/usr/local/include sudo pip install tesserocr
      Collecting tesserocr
        Using cached tesserocr-2.2.2.tar.gz
      Building wheels for collected packages: tesserocr
        Running setup.py bdist_wheel for tesserocr ... error
        Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o86wg2/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpFePVIkpip-wheel- --python-tag cp27:
        Supporting tesseract v4.00.00dev
        Configs from pkg-config: {'libraries': ['lept', 'tesseract'], 'cython_compile_time_env': {'TESSERACT_VERSION': 262144}, 'library_dirs': ['/usr/local/lib'], 'include_dirs': ['/usr/local/include']}
        running bdist_wheel
        running build
        running build_ext
        building 'tesserocr' extension
        creating build
        creating build/temp.linux-x86_64-2.7
        x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/usr/include/python2.7 -c tesserocr.cpp -o build/temp.linux-x86_64-2.7/tesserocr.o -std=c++11
        cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
        tesserocr.cpp: In function ‘void inittesserocr()’:
        tesserocr.cpp:25814:69: error: ‘OEM_CUBE_ONLY’ is not a member of ‘tesseract’
           __pyx_t_1 = __Pyx_PyInt_From_enum__tesseract_3a__3a_OcrEngineMode(tesseract::OEM_CUBE_ONLY); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                             ^
        tesserocr.cpp:25827:69: error: ‘OEM_TESSERACT_CUBE_COMBINED’ is not a member of ‘tesseract’
           __pyx_t_1 = __Pyx_PyInt_From_enum__tesseract_3a__3a_OcrEngineMode(tesseract::OEM_TESSERACT_CUBE_COMBINED); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                             ^
        error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
        
        ----------------------------------------
        Failed building wheel for tesserocr
        Running setup.py clean for tesserocr
      Failed to build tesserocr
      Installing collected packages: tesserocr
        Running setup.py install for tesserocr ... error
          Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o86wg2/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Hh2uA2-record/install-record.txt --single-version-externally-managed --compile:
          Supporting tesseract v4.00.00dev
          Configs from pkg-config: {'libraries': ['lept', 'tesseract'], 'cython_compile_time_env': {'TESSERACT_VERSION': 262144}, 'library_dirs': ['/usr/local/lib'], 'include_dirs': ['/usr/local/include']}
          running install
          running build
          running build_ext
          building 'tesserocr' extension
          creating build
          creating build/temp.linux-x86_64-2.7
          x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/usr/include/python2.7 -c tesserocr.cpp -o build/temp.linux-x86_64-2.7/tesserocr.o -std=c++11
          cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
          tesserocr.cpp: In function ‘void inittesserocr()’:
          tesserocr.cpp:25814:69: error: ‘OEM_CUBE_ONLY’ is not a member of ‘tesseract’
             __pyx_t_1 = __Pyx_PyInt_From_enum__tesseract_3a__3a_OcrEngineMode(tesseract::OEM_CUBE_ONLY); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                               ^
          tesserocr.cpp:25827:69: error: ‘OEM_TESSERACT_CUBE_COMBINED’ is not a member of ‘tesseract’
             __pyx_t_1 = __Pyx_PyInt_From_enum__tesseract_3a__3a_OcrEngineMode(tesseract::OEM_TESSERACT_CUBE_COMBINED); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                               ^
          error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
          
          ----------------------------------------
      Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o86wg2/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Hh2uA2-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-o86wg2/tesserocr/
      root@Ubuntu1:~# 

How do I fix it?

**Comment by sirfz** [comment]
You seem to be compiling against tesseract v4. Have you tried installing the master branch? See #87

**Comment by vatsal28** [comment]
I cloned the master branch only. I'll check it once more, but this would work with tesseract 4.00, right?

**Comment by vatsal28** [comment]
Yes, I was doing setup.py from the master branch and this is what I got:


```
root@Ubuntu1:~/tesserocr# python setup.py build_ext -I/usr/local/include
				Supporting tesseract v4.00.00dev
				Configs from pkg-config: {'libraries': ['lept', 'tesseract'], 'cython_compile_time_env': {'TESSERACT_VERSION': 262144}, 'library_dirs': ['/usr/local/lib'], 'include_dirs': ['/usr/local/include']}
				running build_ext
				Compiling tesserocr.pyx because it changed.
				[1/1] Cythonizing tesserocr.pyx
				building 'tesserocr' extension
				creating build
				creating build/temp.linux-x86_64-2.7
				x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/usr/local/include -I/usr/include/python2.7 -c tesserocr.cpp -o build/temp.linux-x86_64-2.7/tesserocr.o -std=c++11 -DUSE_STD_NAMESPACE
				cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
				creating build/lib.linux-x86_64-2.7
				c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/tesserocr.o -L/usr/local/lib -llept -ltesseract -o build/lib.linux-x86_64-2.7/tesserocr.so
```

And if I enter the python shell and try to import tesserocr, it says module does not exist. I'm not very good with the shell commands so I'm not sure if the above output is an error or what. Because it did not explicitly state an error

**Comment by sirfz** [comment]
You can just do `pip install .` from the repo's directory to install it.

**Comment by vatsal28** [comment]
Thanks! It worked !
