### ISSUE TITLE
fatal error: 'cinttypes' file not found

### ISSUE THREAD

**Issue by xiejun946** [sirfz/tesserocr#164]
python3 -m pip install tesserocr pillow
Collecting tesserocr
  Using cached https://files.pythonhosted.org/packages/f8/6d/4e81e041f33a4419e59edcb1dbdf3c56e9393f60f5ef531381bd67a1339b/tesserocr-2.3.1.tar.gz
Collecting pillow
  Using cached https://files.pythonhosted.org/packages/d1/21/bef2816809fac16754e07ed935469fc65f42ced1a94766de7c804179311d/Pillow-5.3.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: tesserocr, pillow
  Running setup.py install for tesserocr ... error
    Complete output from command /usr/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/1v/r0pq3sh92kjdz3qqnybcpg4r0000gp/T/pip-build-pozupilh/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/1v/r0pq3sh92kjdz3qqnybcpg4r0000gp/T/pip-f45mzq8m-record/install-record.txt --single-version-externally-managed --compile:
    Supporting tesseract v4.0.0
    Configs from pkg-config: {'include_dirs': ['/usr/local/Cellar/leptonica/1.76.0/include', '/usr/local/Cellar/tesseract/4.0.0/include'], 'library_dirs': ['/usr/local/Cellar/leptonica/1.76.0/lib', '/usr/local/Cellar/tesseract/4.0.0/lib'], 'libraries': ['tesseract', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 262144}}
    /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_ext
    building 'tesserocr' extension
    creating build
    creating build/temp.macosx-10.6-intel-3.6
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/usr/local/Cellar/leptonica/1.76.0/include -I/usr/local/Cellar/tesseract/4.0.0/include -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c tesserocr.cpp -o build/temp.macosx-10.6-intel-3.6/tesserocr.o -std=c++11 -DUSE_STD_NAMESPACE
    In file included from tesserocr.cpp:671:
    In file included from /usr/local/Cellar/tesseract/4.0.0/include/tesseract/genericvector.h:28:
    In file included from /usr/local/Cellar/tesseract/4.0.0/include/tesseract/tesscallback.h:22:
    /usr/local/Cellar/tesseract/4.0.0/include/tesseract/host.h:30:10: fatal error: 'cinttypes' file not found
    #include <cinttypes>  // PRId32, ...
             ^~~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1 tesseract -v
tesseract 4.0.0
 leptonica-1.76.0
  libjpeg 9c : libpng 1.6.35 : libtiff 4.0.10 : zlib 1.2.11
 Found AVX2
 Found AVX
 Found SSE
g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

this happen on my mac,when i install tesserocr,and i have install tesserocr ang imagemagick
i have show my tesseract version and gcc version ,anybody to help me?
i have try anybody's answer ,but i do not work

**Comment by xiejun946** [comment]
my mac have both python2.7 and python 3.6  when i run commandCC=clang XCC=clang++ CPPFLAGS="-stdlib=libc++ -DUSE_STD_NAMESPACE -mmacosx-version-min=10.8" pip install tesserocr
it do work andSuccessfully installed tesserocr-2.3.1 but i want the module work in my python3.6
if i run command
CC=clang XCC=clang++ CPPFLAGS="-stdlib=libc++ -DUSE_STD_NAMESPACE -mmacosx-version-min=10.8" python3 -m pip install tesserocr 
it show error as it:
 g++-4.2 -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g -stdlib=libc++ -DUSE_STD_NAMESPACE -mmacosx-version-min=10.8 build/temp.macosx-10.6-intel-3.6/tesserocr.o -L/usr/local/Cellar/leptonica/1.76.0/lib -L/usr/local/Cellar/tesseract/4.0.0/lib -llept -ltesseract -o build/lib.macosx-10.6-intel-3.6/tesserocr.cpython-36m-darwin.so
    unable to execute 'g++-4.2': No such file or directory
    error: command 'g++-4.2' failed with exit status 1

**Comment by xiejun946** [comment]
i have resolved my question by set softlink to it
sudo ln -s /usr/bin/g++ /usr/local/bin/g++-4.2CC=clang XCC=clang++ CPPFLAGS="-stdlib=libc++ -DUSE_STD_NAMESPACE -mmacosx-version-min=10.8" python3 -m pip install tesserocr
but i happen another question
my python alawys exit if i run a    .py

**Comment by WhiteTeaDragon** [comment]
For anyone having the same problem: this also helps:

```
brew install llvm
export CC=$(brew --prefix llvm)/bin/clang
export CXX=$(brew --prefix llvm)/bin/clang++
```

Taken from https://github.com/immunant/c2rust/issues/380
