### ISSUE TITLE
Failure to build with leptonica 1.83

### ISSUE THREAD

**Issue by risicle** [sirfz/tesserocr#314]
Leptonica 1.83 moved a number of `struct` definitions into "private" headers, notably `Pix` and `Box` et al.

This results in a build failure:

```
tesserocr.cpp: In function ‘PyObject* __pyx_f_9tesserocr__pix_to_image(Pix*)’:
tesserocr.cpp:6685:26: error: invalid use of incomplete type ‘struct Pix’
 6685 |   __pyx_t_1 = __pyx_v_pix->informat;
      |                          ^~
```

which requires the inclusion of the header `leptonica/pix_internal.h` to overcome. This can be done with a supplemental `cdef extern from` statement as detailed in https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#referencing-c-header-files @ `tesseract.pxd`

```
cdef extern from "leptonica/allheaders.h" nogil:
    pass

cdef extern from "leptonica/pix_internal.h" nogil:
    struct Pix:
```

I haven't made this a PR with the suggested change because it will presumably need to be conditionally done based on the result of a version test, but the above fix does seem to work.

**Comment by sirfz** [comment]
There already is a version check on the tesseract version [passed as compile-time environment variables](https://github.com/sirfz/tesserocr/blob/3bfa7d9c66985610d8d74c74034689a0460c0aaa/setup.py#LL148C13-L148C29) that yields different cpp code based on some [cython macro checks](https://github.com/sirfz/tesserocr/blob/3bfa7d9c66985610d8d74c74034689a0460c0aaa/tesserocr.pyx#L846), you should be able to apply the same concept for leptonica version-specific changes.

**Comment by nijel** [comment]
1441bec703cf68161acce5e85907ddd71c47fdc3 fixed this.
