### ISSUE TITLE
bits/libc-header-start.h: No such file or directory

### ISSUE THREAD

**Issue by NicoLivesey** [sirfz/tesserocr#130]
Hi everybody, I apologize in advance for the potential duplicate since there is already a huge amount of issues related to environment variables (I assume my problem is related to this) but I can't find one similar to mine.

I work on ubuntu 18.04
`tesseract -v`
```
tesseract 4.0.0-beta.1
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

 Found AVX2
 Found AVX
 Found SSE
```

After cloning master:

`CPPFLAGS=-I/usr/include pip install .`
```
In file included from /home/nicolas/anaconda3/include/python3.6m/Python.h:11:0,
                     from tesserocr.cpp:26:
    /usr/include/limits.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
     #include <bits/libc-header-start.h>
              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

**Comment by NicoLivesey** [comment]
Ok, fixed this by doing the following (sorry my machine is very young):
`sudo apt-get install gcc-multilib g++-multilib`

Now I have this:
```
tesserocr.cpp:601:10: fatal error: tesseract/publictypes.h: No such file or directory
     #include "tesseract/publictypes.h"
              ^~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

I will try to keep this issue updated since it is not completely solved for the moment.

**Comment by NicoLivesey** [comment]
Fixed this with this:
`sudo apt-get install libtesseract-dev`

We are here now:
```
    /home/nicolas/anaconda3/compiler_compat/ld: cannot find -llept
    /home/nicolas/anaconda3/compiler_compat/ld: cannot find -ltesseract
    collect2: error: ld returned 1 exit status
    error: command 'g++' failed with exit status 1
```

**Comment by nenandjabhata** [comment]
You Can solve it by installing this :
`└─# sudo apt-get install gcc-multilib   `
