### ISSUE TITLE
GetBestLSTMSymbolChoices() causes Python to crash

### ISSUE THREAD

**Issue by Skullblaca** [sirfz/tesserocr#241]
Good afternoon,

I am currently trying to get the LSTM and Legacy Confidences for single letters. Therefore, I wrote a program that would randomly generate images of letters and have tesserocr extract the choices while set on DEFAULT mode. 

I cannot run 100 letters in a loop, because my Python program always crashes. It does so without Traceback, which makes it difficult to debug.

Having commented different sections of my code and testing it, I have singled out the line where the program crashes:
`choices = ri.GetBestLSTMSymbolChoices()`
However, it does not always crash on this line. It does so roughly every 30 times. So I was digging deeper to find the underlying issues.

I have a strong feeling that it might come from line 1050 in tesserocr.pyx:
`output = self._riter.GetBestLSTMSymbolChoices()[0]`
Here is a hardcoded index `[0]`, which probably throws an error, if the list is empty.

Looking at the code from tesseract: (which I don't fully understand, because I'm not good with C++)
` std::vector<std::vector<std::pair<const char*, float>>>*
 ResultIterator::GetBestLSTMSymbolChoices() const {
   if (it_->word() != nullptr) {
     return &it_->word()->CTC_symbol_choices;
   } else {
     return nullptr;
   }
 }`
I think the `self._riter.GetBestLSTMSymbolChoices()` might also return a Null-Pointer in tesseract (or maybe an empty array). Could it be that this is not correctly handled in the tesserocr module?

**Comment by sirfz** [comment]
Thank you for digging in the tesseract code and providing details. I've pushed changes that should fix this issue. Please let me know if this fix is good.

**Comment by Skullblaca** [comment]
How can I download the 2.5.2b version of the module? Then I can test it with my script.
Pip only has 2.5.1 available.

**Comment by sirfz** [comment]
You can pip install git+https://github.com/sirfz/tesserocr.git

**Comment by Skullblaca** [comment]
tesserocr.cpp(837): fatal error C1083: Cannot open include file: 'leptonica/allheaders.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

I had the same problem with the initial installation of the module. When I used the wheel file it worked. Maybe there is something wrong with my tesseract installation. But I can't find a proper explanation on how to install leptonica on my windows-laptop.
Also I don't see what's the issue, since it's actually working fine with version 2.4.0 via the wheel file

**Comment by sirfz** [comment]
I wasn't aware you're on Windows, pip install won't work out of the box. I'll make a release with this fix this week (all tests passed for the build) so you can install it via Conda.

**Comment by Skullblaca** [comment]
Alright cool, thank you!
