### ISSUE TITLE
Build with tesseract-4.0.0-beta-3 fails, missing include file osdetect.h, easy fix

### ISSUE THREAD

**Issue by shentonfreude** [sirfz/tesserocr#129]
I've built tesseract-4 from source on my Mac, and done the "make install" thing:
```
$ tesseract -v
tesseract 4.0.0-beta.3-180-gab1f
 leptonica-1.76.0
  libjpeg 9c : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11
 Found AVX2
 Found AVX
 Found SSE
```

For tesserocr, I create a virtualenv with python3.6, and see pip failing, first with a warning, then with an error:
```
(.venv3) $ pip install tesserocr
...
    In file included from tesserocr.cpp:621:
    In file included from /usr/local/Cellar/leptonica/1.76.0/include/leptonica/allheaders.h:35:
    In file included from /usr/local/Cellar/leptonica/1.76.0/include/leptonica/alltypes.h:37:
    /usr/local/Cellar/leptonica/1.76.0/include/leptonica/environ.h:158:10: warning: 'HAVE_FSTATAT' macro redefined [-Wmacro-redefined]
    #define  HAVE_FSTATAT     0
             ^
    /Users/chris/.pyenv/versions/3.6.3/include/python3.6m/pyconfig.h:319:9: note: previous definition is here
    #define HAVE_FSTATAT 1
            ^
    tesserocr.cpp:635:10: fatal error: 'tesseract/osdetect.h' file not found
    #include "tesseract/osdetect.h"
```

I can fix the build by copying the osdetect.h file from my tesseract source to my system includes directory:
```
(.venv3) $ cp ./tesseract/src/ccmain/osdetect.h /usr/local/include/tesseract/
(.venv3) $ pip install tesserocr
Collecting tesserocr
Building wheels for collected packages: tesserocr
  Running setup.py bdist_wheel for tesserocr ... done
  ...
Successfully built tesserocr
Installing collected packages: tesserocr
Successfully installed tesserocr-2.3.0
```

I'm not familiar enough with how Tesseract is evolving to understand if this file was forgotten in the "make install" process or it's something that can be worked around in tessocr.

Thanks.

**Comment by amitdo** [comment]
Also see:
https://github.com/tesseract-ocr/tesseract/issues/1773
